-- Reference Data for Company
MERGE INTO [dbo].[Companies] AS Target USING
(VALUES
  (N'1PG', N'1-PAGE LIMITED', N'Software & Services'),
  (N'ONT', N'1300 SMILES LIMITED', N'Health Care Equipment & Services'),
  (N'TGP', N'360 CAPITAL GROUP', N'Real Estate'),
  (N'TIX', N'360 CAPITAL INDUSTRIAL FUND', N'Real Estate'),
  (N'TOF', N'360 CAPITAL OFFICE FUND', N'Real Estate'),
  (N'TOT', N'360 CAPITAL TOTAL RETURN FUND', N'Class Pend'),
  (N'3DM', N'3D MEDICAL LIMITED', N'Health Care Equipment & Services'),
  (N'TDO', N'3D OIL LIMITED', N'Energy'),
  (N'DDD', N'3D RESOURCES LIMITED', N'Materials'),
  (N'3PL', N'3P LEARNING LIMITED..', N'Consumer Services'),
  (N'88E', N'88 ENERGY LIMITED', N'Energy'),
  (N'8CO', N'8COMMON LIMITED', N'Software & Services'),
  (N'8IH', N'8I HOLDINGS LTD', N'Diversified Financials'),
  (N'NNW', N'99 WUXIAN LIMITED', N'Retailing'),
  (N'ACB', N'A-CAP RESOURCES LIMITED', N'Energy'),
  (N'AYC', N'A1 CONSOLIDATED GOLD LIMITED', N'Materials'),
  (N'AYI', N'A1 INVESTMENTS & RESOURCES LTD', N'Diversified Financials'),
  (N'AAT', N'AAT CORPORATION LIMITED', N'Technology Hardware & Equipment'),
  (N'ABP', N'ABACUS PROPERTY GROUP', N'Real Estate'),
  (N'ALR', N'ABERDEEN LEADERS LIMITED', N'Diversified Financials'),
  (N'ABL', N'ABILENE OIL AND GAS LIMITED', N'Energy'),
  (N'ABU', N'ABM RESOURCES NL', N'Materials'),
  (N'AJC', N'ACACIA COAL LIMITED', N'Energy'),
  (N'AKG', N'ACADEMIES AUSTRALASIA GROUP LIMITED', N'Consumer Services'),
  (N'ACS', N'ACCENT RESOURCES NL', N'Materials'),
  (N'ACX', N'ACONEX LIMITED', N'Software & Services'),
  (N'ACQ', N'ACORN CAPITAL INVESTMENT FUND LIMITED', N'Not Applic'),
  (N'ACR', N'ACRUX LIMITED', N'Pharmaceuticals & Biotechnology'),
  (N'ACW', N'ACTINOGEN LIMITED', N'Materials'),
  (N'AIV', N'ACTIVEX LIMITED', N'Materials'),
  (N'ACU', N'ACUVAX LIMITED', N'Pharmaceuticals & Biotechnology'),
  (N'ADA', N'ADACEL TECHNOLOGIES LIMITED', N'Software & Services'),
  (N'ADD', N'ADAVALE RESOURCES LIMITED', N'Energy'),
  (N'AAU', N'ADCORP AUSTRALIA LIMITED', N'Media'),
  (N'ABC', N'ADELAIDE BRIGHTON LIMITED', N'Materials'),
  (N'ADN', N'ADELAIDE RESOURCES LIMITED', N'Materials'),
  (N'ADQ', N'ADG GLOBAL SUPPLY LIMITED.', N'Capital Goods'),
  (N'ABY', N'ADITYA BIRLA MINERALS LIMITED', N'Materials'),
  (N'AHZ', N'ADMEDUS LTD', N'Health Care Equipment & Services'),
  (N'ADY', N'ADMIRALTY RESOURCES NL.', N'Materials'),
  (N'ADJ', N'ADSLOT LTD', N'Software & Services'),
  (N'ABV', N'ADVANCED BRAKING TECHNOLOGY LTD', N'Automobiles & Components'),
  (N'AES', N'ADVANCED ENERGY SYSTEMS LIMITED', N'Real Estate'),
  (N'ACE', N'ADVANCED ENGINE COMPONENTS LIMITED', N'Automobiles & Components'),
  (N'ASW', N'ADVANCED SHARE REGISTRY LIMITED', N'Diversified Financials'),
  (N'ADX', N'ADX ENERGY LTD', N'Energy'),
  (N'AED', N'AED OIL LIMITED', N'Energy'),
  (N'AER', N'AEERIS LTD', N'Class Pend'),
  (N'AQR', N'AEON METALS LIMITED', N'Materials'),
  (N'AEI', N'AERIS ENVIRONMENTAL LTD', N'Commercial Services & Supplies'),
  (N'AFJ', N'AFFINITY EDUCATION GROUP LIMITED', N'Consumer Services'),
  (N'AFR', N'AFRICAN ENERGY RESOURCES LIMITED', N'Energy'),
  (N'AFT', N'AFT CORPORATION LIMITED', N'Capital Goods'),
  (N'AHA', N'AG FINANCIAL LTD', N'Diversified Financials'),
  (N'AGX', N'AGENIX LIMITED', N'Pharmaceuticals & Biotechnology'),
  (N'AGL', N'AGL ENERGY LIMITED.', N'Utilities'),
  (N'AGH', N'AGRI - TRADE HOLDINGS LIMITED', N'Real Estate'),
  (N'AGJ', N'AGRICULTURAL LAND TRUST', N'Real Estate'),
  (N'AMN', N'AGRIMIN LIMITED', N'Materials'),
  (N'AGR', N'AGUIA RESOURCES LIMITED', N'Materials'),
  (N'APW', N'AIMS PROPERTY SECURITIES FUND', N'Real Estate'),
  (N'AGI', N'AINSWORTH GAME TECHNOLOGY LIMITED', N'Consumer Services'),
  (N'AHJ', N'AIR CHANGE INTERNATIONAL LIMITED', N'Capital Goods'),
  (N'AIZ', N'AIR NEW ZEALAND LIMITED', N'Transportation'),
  (N'AJL', N'AJ LUCAS GROUP LIMITED', N'Capital Goods'),
  (N'AQG', N'ALACER GOLD CORP.', N'Materials'),
  (N'AUQ', N'ALARA RESOURCES LIMITED', N'Materials'),
  (N'ACL', N'ALCHEMIA LIMITED', N'Pharmaceuticals & Biotechnology'),
  (N'ALY', N'ALCHEMY RESOURCES LIMITED', N'Materials'),
  (N'AAI', N'ALCOA INC.', N'Materials'),
  (N'AYN', N'ALCYONE RESOURCES LTD', N'Materials'),
  (N'LEP', N'ALE PROPERTY GROUP', N'Real Estate'),
  (N'AWD', N'ALEATOR ENERGY LIMITED', N'Energy'),
  (N'AJX', N'ALEXIUM INTERNATIONAL GROUP LIMITED', N'Materials'),
  (N'AEB', N'ALGAE.TEC LIMITED', N'Energy'),
  (N'AQI', N'ALICANTO MINERALS LIMITED', N'Materials'),
  (N'ALK', N'ALKANE RESOURCES LIMITED', N'Materials'),
  (N'AHQ', N'ALLEGIANCE COAL LIMITED', N'Energy'),
  (N'AMT', N'ALLEGRA ORTHOPAEDICS LIMITED', N'Health Care Equipment & Services'),
  (N'AQZ', N'ALLIANCE AVIATION SERVICES LIMITED', N'Transportation'),
  (N'AGS', N'ALLIANCE RESOURCES LIMITED', N'Materials'),
  (N'AGE', N'ALLIGATOR ENERGY LIMITED', N'Energy'),
  (N'AZG', N'ALLMINE GROUP LIMITED', N'Commercial Services & Supplies'),
  (N'AYR', N'ALLOY RESOURCES LIMITED', N'Materials'),
  (N'ALQ', N'ALS LIMITED', N'Commercial Services & Supplies'),
  (N'ARS', N'ALT RESOURCES LIMITED', N'Class Pend'),
  (N'ATC', N'ALTECH CHEMICALS LTD', N'Materials'),
  (N'AIQ', N'ALTERNATIVE INVESTMENT TRUST', N'Not Applic'),
  (N'ALU', N'ALTIUM LIMITED', N'Software & Services'),
  (N'AOH', N'ALTONA MINING LIMITED', N'Materials'),
  (N'AJM', N'ALTURA MINING LIMITED', N'Materials'),
  (N'AWC', N'ALUMINA LIMITED', N'Materials'),
  (N'AMA', N'AMA GROUP LIMITED', N'Retailing'),
  (N'AHD', N'AMALGAMATED HOLDINGS LIMITED', N'Media'),
  (N'AMO', N'AMBERTECH LIMITED', N'Technology Hardware & Equipment'),
  (N'AMB', N'AMBITION GROUP LIMITED', N'Commercial Services & Supplies'),
  (N'AMH', N'AMCIL LIMITED', N'Diversified Financials'),
  (N'AMM', N'AMCOM TELECOMMUNICATIONS LIMITED', N'Telecommunication Services'),
  (N'AMC', N'AMCOR LIMITED', N'Materials'),
  (N'AOW', N'AMERICAN PATRIOT OIL & GAS LIMITED', N'Energy'),
  (N'AXZ', N'AMEX RESOURCES LIMITED', N'Materials'),
  (N'AGF', N'AMP CAPITAL CHINA GROWTH FUND', N'Diversified Financials'),
  (N'AMP', N'AMP LIMITED', N'Insurance'),
  (N'ANQ', N'ANAECO LIMITED', N'Commercial Services & Supplies'),
  (N'ALT', N'ANALYTICA LIMITED', N'Health Care Equipment & Services'),
  (N'ANR', N'ANATARA LIFESCIENCES LTD', N'Pharmaceuticals & Biotechnology'),
  (N'AEK', N'ANATOLIA ENERGY LIMITED', N'Energy'),
  (N'AHR', N'ANCHOR RESOURCES LIMITED', N'Materials'),
  (N'ATM', N'ANEKA TAMBANG (PERSERO) TBK (PT)', N'Materials'),
  (N'AQM', N'ANGLO AMERICAN CAPITAL PLC', N'Not Applic'),
  (N'AAR', N'ANGLO AUSTRALIAN RESOURCES NL', N'Materials'),
  (N'AGG', N'ANGLOGOLD ASHANTI LIMITED', N'Materials'),
  (N'AB1', N'ANIMOCA BRANDS CORPORATION LIMITED', N'Software & Services'),
  (N'AWV', N'ANOVA METALS LIMITED', N'Materials'),
  (N'ANN', N'ANSELL LIMITED', N'Health Care Equipment & Services'),
  (N'AZZ', N'ANTARES ENERGY LIMITED', N'Energy'),
  (N'AWW', N'ANTARES MINING LIMITED', N'Materials'),
  (N'ANO', N'ANTARIA LIMITED', N'Materials'),
  (N'ADO', N'ANTEO DIAGNOSTICS LIMITED', N'Health Care Equipment & Services'),
  (N'AVD', N'ANTILLES OIL AND GAS NL', N'Energy'),
  (N'AZY', N'ANTIPA MINERALS LIMITED', N'Materials'),
  (N'ANP', N'ANTISENSE THERAPEUTICS LIMITED', N'Pharmaceuticals & Biotechnology'),
  (N'APE', N'AP EAGERS LIMITED', N'Retailing'),
  (N'APA', N'APA GROUP', N'Utilities'),
  (N'AAL', N'APAC COAL LIMITED', N'Energy'),
  (N'AQQ', N'APHRODITE GOLD LIMITED', N'Materials'),
  (N'APN', N'APN NEWS & MEDIA LIMITED', N'Media'),
  (N'APO', N'APN OUTDOOR GROUP LIMITED', N'Media'),
  (N'APD', N'APN PROPERTY GROUP LIMITED', N'Diversified Financials'),
  (N'AOP', N'APOLLO CONSOLIDATED LIMITED', N'Materials'),
  (N'AON', N'APOLLO MINERALS LIMITED', N'Materials'),
  (N'AOY', N'APOLLO SERIES 2007-1E TRUST', N'Not Applic'),
  (N'AOJ', N'APOLLO SERIES 2010-1 TRUST', N'Not Applic'),
  (N'AOR', N'APOLLO SERIES 2013-1 TRUST', N'Not Applic'),
  (N'APX', N'APPEN LIMITED', N'Software & Services'),
  (N'ALA', N'APPLABS TECHNOLOGIES LTD', N'Software & Services'),
  (N'AQH', N'APT PIPELINES LIMITED.', N'Not Applic'),
  (N'AQU', N'AQUAINT CAPITAL HOLDINGS LIMITED', N'Consumer Services'),
  (N'AQP', N'AQUARIUS PLATINUM LIMITED', N'Materials'),
  (N'ARU', N'ARAFURA RESOURCES LIMITED', N'Materials'),
  (N'ARP', N'ARB CORPORATION LIMITED', N'Automobiles & Components'),
  (N'ARX', N'ARC EXPLORATION LIMITED', N'Materials'),
  (N'AXE', N'ARCHER EXPLORATION LIMITED', N'Materials'),
  (N'AAD', N'ARDENT LEISURE GROUP', N'Consumer Services'),
  (N'AWO', N'ARDENT RESOURCES LTD', N'Materials'),
  (N'ADV', N'ARDIDEN LTD', N'Materials'),
  (N'ARF', N'ARENA REIT.', N'Real Estate'),
  (N'ARD', N'ARGENT MINERALS LIMITED', N'Materials'),
  (N'AXT', N'ARGO EXPLORATION LIMITED', N'Materials'),
  (N'ARG', N'ARGO INVESTMENTS LIMITED', N'Not Applic'),
  (N'ARE', N'ARGONAUT RESOURCES NL', N'Materials'),
  (N'AGY', N'ARGOSY MINERALS LIMITED', N'Materials'),
  (N'ARA', N'ARIADNE AUSTRALIA LIMITED', N'Commercial Services & Supplies'),
  (N'ALL', N'ARISTOCRAT LEISURE LIMITED', N'Consumer Services'),
  (N'ARJ', N'ARK FUND LIMITED (THE)', N'Real Estate'),
  (N'AHK', N'ARK MINES LIMITED', N'Materials'),
  (N'AIK', N'ARMIDALE INVESTMENT CORPORATION LIMITED', N'Not Applic'),
  (N'AJQ', N'ARMOUR ENERGY LIMITED', N'Energy'),
  (N'AWQ', N'AROWANA AUSTRALASIAN VALUE OPPORTUNITIES FUND LIMITED', N'Not Applic'),
  (N'AWN', N'AROWANA INTERNATIONAL LIMITED', N'Capital Goods'),
  (N'ARI', N'ARRIUM LIMITED', N'Materials'),
  (N'ARV', N'ARTEMIS RESOURCES LIMITED', N'Materials'),
  (N'AAJ', N'ARUMA RESOURCES LIMITED', N'Materials'),
  (N'AJR', N'ARUNTA RESOURCES LIMITED', N'Materials'),
  (N'AHY', N'ASALEO CARE LIMITED', N'Household & Personal Products'),
  (N'AJY', N'ASAPLUS RESOURCES LIMITED', N'Materials'),
  (N'AIO', N'ASCIANO LIMITED', N'Transportation'),
  (N'AZQ', N'ASCOT RESOURCES LIMITED', N'Materials'),
  (N'AFA', N'ASF GROUP LIMITED', N'Diversified Financials'),
  (N'ASZ', N'ASG GROUP LIMITED', N'Software & Services'),
  (N'ASH', N'ASHLEY SERVICES GROUP LIMITED', N'Commercial Services & Supplies'),
  (N'AJD', N'ASIA PACIFIC DATA CENTRE GROUP', N'Real Estate'),
  (N'DIG', N'ASIA PACIFIC DIGITAL LIMITED', N'Media'),
  (N'AJJ', N'ASIAN AMERICAN MEDICAL GROUP LIMITED', N'Health Care Equipment & Services'),
  (N'ATB', N'ASIAN DEVELOPMENT BANK', N'Not Applic'),
  (N'AUF', N'ASIAN MASTERS FUND LIMITED', N'Diversified Financials'),
  (N'AKF', N'ASK FUNDING LIMITED', N'Diversified Financials'),
  (N'APZ', N'ASPEN GROUP', N'Real Estate'),
  (N'ASP', N'ASPERMONT LIMITED.', N'Media'),
  (N'AKM', N'ASPIRE MINING LIMITED', N'Materials'),
  (N'AIR', N'ASTIVITA LIMITED', N'Capital Goods'),
  (N'AJA', N'ASTRO JAPAN PROPERTY GROUP', N'Real Estate'),
  (N'ARO', N'ASTRO RESOURCES NL', N'Materials'),
  (N'ATR', N'ASTRON CORPORATION LIMITED', N'Materials'),
  (N'ASX', N'ASX LIMITED', N'Diversified Financials'),
  (N'ACG', N'ATCOR MEDICAL HOLDINGS LIMITED', N'Health Care Equipment & Services'),
  (N'AHN', N'ATHENA RESOURCES LIMITED', N'Materials'),
  (N'ATI', N'ATLANTIC LIMITED', N'Materials'),
  (N'AGO', N'ATLAS IRON LIMITED', N'Materials'),
  (N'ATP', N'ATLAS PEARLS AND PERFUMES LTD', N'Consumer Durables & Apparel'),
  (N'ATU', N'ATRUM COAL NL', N'Materials'),
  (N'AYA', N'ATTILA RESOURCES LIMITED', N'Materials'),
  (N'AIA', N'AUCKLAND INTERNATIONAL AIRPORT LIMITED', N'Transportation'),
  (N'ACP', N'AUDALIA RESOURCES LIMITED', N'Materials'),
  (N'AKP', N'AUDIO PIXELS HOLDINGS LIMITED', N'Consumer Durables & Apparel'),
  (N'AUK', N'AUGUR RESOURCES LIMITED', N'Materials'),
  (N'AEE', N'AURA ENERGY LIMITED', N'Energy')
)
AS SOURCE ([Code], [Name], [Group])
ON Target.[Code] = Source.[Code]

-- Update matched rows
WHEN MATCHED THEN
UPDATE SET [Code] = Source.[Code],
           [Name] = Source.[Name],
           [Group] = Source.[Group]

-- Insert new rows
WHEN NOT MATCHED BY TARGET THEN
INSERT ([Code], [Name], [Group])
VALUES (Source.[Code], Source.[Name], Source.[Group]);