DELETE FROM [dbo].[IndustryGroup]

-- Insert Reference Data for IndustryGroup
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Automobiles & Components')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Banks')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Capital Goods')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Class Pend')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Commercial Services & Supplies')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Consumer Durables & Apparel')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Consumer Services')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Diversified Financials')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Energy')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Food & Staples Retailing')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Food, Beverage & Tobacco')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Health Care Equipment & Services')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Household & Personal Products')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Insurance')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Materials')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Media')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Not Applic')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Pharmaceuticals & Biotechnology')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Real Estate')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Retailing')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Semiconductors & Semiconductor Equipment')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Software & Services')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Technology Hardware & Equipment')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Telecommunication Services')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Transportation')
INSERT INTO [dbo].[IndustryGroup] ([Group]) VALUES (N'Utilities')